#!/usr/bin/env bash
#
# arch-update - Atualiza o Arch Linux
#
# Site:       https://github.com/linuxjeff/arch-update
# Autor:      Jefferson Vitor de Santana
# Manutenção: Jefferson Vitor de Santana
#
# ------------------------------------------------------------------------ #
#  Este programa atualiza pacotes do Pacman, Aur, flatpak e Snap.
#
#  Exemplos:
#      $ ach-update
#      Neste exemplo o script faz a atualização dos pacotes.
# ------------------------------------------------------------------------ #
# Histórico:
#
#   v0.0.1 15/12/2020, Jefferson:
#       - Início do programa
# ------------------------------------------------------------------------ #
# Testado em:
#   bash 4.4.19
# ------------------------------------------------------------------------ #
# Agradecimentos:
#
# ------------------------------------------------------------------------ #
